name = "cinebook"
main = "worker.js"
compatibility_date = "2026-09-01"

# Cloudflare Static Assets for Single-Page React App
assets = { directory = "./frontend/dist", binding = "ASSETS", not_found_handling = "single-page-application" }

[build]
command = "cd frontend && npm install && npm run build"

[vars]
VITE_API_URL = "https://cinebook-backend-i2k9.onrender.com/api/v1"
