# Catalog Seed Data for CineBook — Top 6 Tollywood Pan-India Hits & 22 Theatres

SEED_MOVIES = [
    {
        "id": "mov-pushpa-2",
        "title": "Pushpa 2: The Rule (2024)",
        "slug": "pushpa-2-the-rule",
        "tagline": "The Rule Begins • Wildfire on Screen",
        "description": "Pushpa Raj expands his red sandalwood empire beyond borders, clashing in an intense battle of power and wits with SP Bhanwar Singh Shekhawat. A high-octane mass action thriller celebrating Indian cinema's biggest icon.",
        "genres": ["Action", "Crime", "Drama", "Thriller"],
        "languages": ["Telugu", "Hindi", "Tamil", "Malayalam", "Kannada"],
        "formats": ["4K Dolby Atmos", "IMAX 3D", "2D", "4DX"],
        "duration": "3h 20m",
        "duration_minutes": 200,
        "release_date": "2024-12-05",
        "rating": 9.6,
        "votes": "520.8K",
        "censor_rating": "UA 16+",
        "poster_url": "/posters/pushpa2.jpg",
        "backdrop_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=1kVK0MZlbI4",
        "director": "Sukumar",
        "cast": [
            {"name": "Allu Arjun", "role": "Pushpa Raj", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Rashmika Mandanna", "role": "Srivalli", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"},
            {"name": "Fahadh Faasil", "role": "SP Bhanwar Singh Shekhawat", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"},
            {"name": "Jagapathi Babu", "role": "Prime Antagonist", "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    },
    {
        "id": "mov-devara-1",
        "title": "Devara: Part 1 (2024)",
        "slug": "devara-part-1",
        "tagline": "Fear and Valour of the Red Sea",
        "description": "In the fearless coastal lands, a heroic sea warrior vows to protect his people from corruption and betrayal, triggering an unstoppable generational battle across treacherous waters.",
        "genres": ["Action", "Drama", "Thriller"],
        "languages": ["Telugu", "Hindi", "Tamil", "Malayalam", "Kannada"],
        "formats": ["4K Dolby Atmos", "IMAX 3D", "2D"],
        "duration": "2h 58m",
        "duration_minutes": 178,
        "release_date": "2024-09-27",
        "rating": 9.3,
        "votes": "410.2K",
        "censor_rating": "UA 16+",
        "poster_url": "/posters/devara.jpg",
        "backdrop_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=pKctPN339Jg",
        "director": "Koratala Siva",
        "cast": [
            {"name": "Jr NTR", "role": "Devara / Vara", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Janhvi Kapoor", "role": "Thangam", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"},
            {"name": "Saif Ali Khan", "role": "Bhaira", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    },
    {
        "id": "mov-kalki-2898",
        "title": "Kalki 2898 AD (2024)",
        "slug": "kalki-2898-ad",
        "tagline": "The Future Begins in 2898 AD",
        "description": "In a dystopian futuristic world where Kasi is the last surviving city under the ruthless rule of the Complex, the immortal warrior Ashwatthama rises to safeguard the prophesied avatar from supreme tyrant Supreme Yaskin.",
        "genres": ["Sci-Fi", "Action", "Mythology"],
        "languages": ["Telugu", "Hindi", "Tamil", "Malayalam", "Kannada"],
        "formats": ["IMAX 3D", "4K Dolby Atmos", "2D", "4DX"],
        "duration": "3h 01m",
        "duration_minutes": 181,
        "release_date": "2024-06-27",
        "rating": 9.5,
        "votes": "640.1K",
        "censor_rating": "UA",
        "poster_url": "/posters/kalki.webp",
        "backdrop_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=kQDd1AhGIHk",
        "director": "Nag Ashwin",
        "cast": [
            {"name": "Prabhas", "role": "Bhairava", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Amitabh Bachchan", "role": "Ashwatthama", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"},
            {"name": "Deepika Padukone", "role": "SUM-80", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"},
            {"name": "Kamal Haasan", "role": "Supreme Yaskin", "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    },
    {
        "id": "mov-salaar-1",
        "title": "Salaar: Part 1 – Ceasefire (2023)",
        "slug": "salaar-part-1-ceasefire",
        "tagline": "The Most Violent Man • Khansaar Awaits",
        "description": "Set in the ruthless fortified dystopian kingdom of Khansaar, childhood comrades Deva and Varadha become bound by blood and vengeance as clans fight for sovereign power.",
        "genres": ["Action", "Crime", "Drama"],
        "languages": ["Telugu", "Hindi", "Tamil", "Malayalam", "Kannada"],
        "formats": ["4K Dolby Atmos", "2D"],
        "duration": "2h 55m",
        "duration_minutes": 175,
        "release_date": "2023-12-22",
        "rating": 9.1,
        "votes": "480.0K",
        "censor_rating": "A",
        "poster_url": "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop",
        "backdrop_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=4GPvYMKtrtI",
        "director": "Prashanth Neel",
        "cast": [
            {"name": "Prabhas", "role": "Deva / Salaar", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Prithviraj Sukumaran", "role": "Varadharaja Mannaar", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"},
            {"name": "Shruti Haasan", "role": "Aadya", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    },
    {
        "id": "mov-og-2025",
        "title": "OG: They Call Him OG (2025)",
        "slug": "og-they-call-him-og",
        "tagline": "The Original Gangster Returns to Mumbai",
        "description": "A legendary samurai-armed gangster named Ojas Gambheera reappears in Mumbai after a decade of exile to dismantle a ruthless international crime syndicate threatening his loyalists.",
        "genres": ["Action", "Crime", "Thriller"],
        "languages": ["Telugu", "Hindi", "Tamil", "Malayalam"],
        "formats": ["4K Dolby Atmos", "2D"],
        "duration": "2h 45m",
        "duration_minutes": 165,
        "release_date": "2025-03-27",
        "rating": 9.7,
        "votes": "390.4K",
        "censor_rating": "UA 16+",
        "poster_url": "/posters/og.jpg",
        "backdrop_url": "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=ZfK4_36bW34",
        "director": "Sujeeth",
        "cast": [
            {"name": "Pawan Kalyan", "role": "Ojas Gambheera (OG)", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Emraan Hashmi", "role": "Omi Bhau", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"},
            {"name": "Priyanka Mohan", "role": "Kalyani", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    },
    {
        "id": "mov-game-changer",
        "title": "Game Changer (2025)",
        "slug": "game-changer",
        "tagline": "An Honest Officer's Rebellion Against the System",
        "description": "An uncompromising Indian Administrative Service (IAS) officer fights against deep-rooted election malpractices and political corruption to guarantee clean governance for common citizens.",
        "genres": ["Action", "Drama", "Political"],
        "languages": ["Telugu", "Hindi", "Tamil"],
        "formats": ["4K Dolby Atmos", "2D"],
        "duration": "2h 50m",
        "duration_minutes": 170,
        "release_date": "2025-01-10",
        "rating": 9.2,
        "votes": "310.5K",
        "censor_rating": "UA",
        "poster_url": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=800&auto=format&fit=crop",
        "backdrop_url": "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=1600&auto=format&fit=crop",
        "trailer_url": "https://www.youtube.com/watch?v=2K4Vb2p7k1M",
        "director": "S. Shankar",
        "cast": [
            {"name": "Ram Charan", "role": "Ram Nandan IAS / Appanna", "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop"},
            {"name": "Kiara Advani", "role": "Deepika", "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop"},
            {"name": "SJ Suryah", "role": "Minister Ramakanth", "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop"}
        ],
        "status": "NOW_SHOWING",
        "is_featured": True,
        "cities": ["guntur", "vijayawada", "tenali"]
    }
]

# # EXCLUSIVE THEATRE: SIVA CINEMAS (449-SEAT BOOKMYSHOW BLUEPRINT)
SEED_THEATRES = [
    {
        "id": "th-gtr-001",
        "name": "Siva Cinemas",
        "slug": "siva-cinemas-guntur",
        "city": "guntur",
        "address": "Near Old Bus Stand, Guntur",
        "facilities": ["4K Laser Projection", "Dolby Atmos", "Pushback Seats", "Parking", "Canteen"],
        "distance": "1.2 km away",
        "cancellation_policy": "Refundable up to 2 hours before showtime",
        "screens": [{"id": "scr-gtr-01", "name": "Screen 1 4K Laser", "sound": "Dolby Atmos", "total_seats": 449}],
        "is_active": True
    }
]

SEED_SHOWS = [
    {
        "id": "sh-gtr-01",
        "movie_id": "mov-pushpa-2",
        "theatre_id": "th-gtr-001",
        "theatre_name": "Siva Cinemas",
        "screen_name": "Screen 1 4K Laser",
        "screen_id": "scr-gtr-01",
        "format": "4K Dolby Atmos",
        "language": "Telugu",
        "show_date": "2026-09-02",
        "show_time": "11:00 AM",
        "tier_price": {"BALCONY": 147, "SECOND_CLASS": 84},
        "convenience_fee_per_ticket": 0.0,
        "tax_percentage": 18.0,
        "availability": "AVAILABLE",
        "is_active": True
    },
    {
        "id": "sh-gtr-02",
        "movie_id": "mov-devara-1",
        "theatre_id": "th-gtr-001",
        "theatre_name": "Siva Cinemas",
        "screen_name": "Screen 1 4K Laser",
        "screen_id": "scr-gtr-01",
        "format": "4K Dolby Atmos",
        "language": "Telugu",
        "show_date": "2026-09-02",
        "show_time": "02:30 PM",
        "tier_price": {"BALCONY": 147, "SECOND_CLASS": 84},
        "convenience_fee_per_ticket": 0.0,
        "tax_percentage": 18.0,
        "availability": "FILLING_FAST",
        "is_active": True
    },
    {
        "id": "sh-gtr-03",
        "movie_id": "mov-kalki-2898",
        "theatre_id": "th-gtr-001",
        "theatre_name": "Siva Cinemas",
        "screen_name": "Screen 1 4K Laser",
        "screen_id": "scr-gtr-01",
        "format": "4K Dolby Atmos",
        "language": "Telugu",
        "show_date": "2026-09-02",
        "show_time": "06:15 PM",
        "tier_price": {"BALCONY": 147, "SECOND_CLASS": 84},
        "convenience_fee_per_ticket": 0.0,
        "tax_percentage": 18.0,
        "availability": "AVAILABLE",
        "is_active": True
    },
    {
        "id": "sh-gtr-04",
        "movie_id": "mov-og-2025",
        "theatre_id": "th-gtr-001",
        "theatre_name": "Siva Cinemas",
        "screen_name": "Screen 1 4K Laser",
        "screen_id": "scr-gtr-01",
        "format": "4K Dolby Atmos",
        "language": "Telugu",
        "show_date": "2026-09-02",
        "show_time": "09:45 PM",
        "tier_price": {"BALCONY": 147, "SECOND_CLASS": 84},
        "convenience_fee_per_ticket": 0.0,
        "tax_percentage": 18.0,
        "availability": "AVAILABLE",
        "is_active": True
    }
]

SEED_EVENTS = [
    {
        "id": "eve-001",
        "title": "Telugu Comedy Fest — Live Standup Special",
        "category": "Standup Comedy",
        "city": "guntur",
        "venue": "Sri Venkateswara Vignana Mandiram, Guntur",
        "date": "2025-03-22",
        "time": "19:00",
        "banner_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop",
        "price_starting": 499.0,
        "description": "An evening of non-stop Telugu comedy, relatable middle-class humor, and hilarious storytelling.",
        "is_featured": True,
        "is_active": True
    },
    {
        "id": "eve-002",
        "title": "Anirudh Live in Concert — Hukum Tour",
        "category": "Music Concert",
        "city": "vijayawada",
        "venue": "Indira Gandhi Municipal Stadium, MG Road, Vijayawada",
        "date": "2025-04-12",
        "time": "18:30",
        "banner_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop",
        "price_starting": 999.0,
        "description": "Rockstar Anirudh Ravichander live in Andhra Pradesh with explosive visual effects, bass, and chartbuster Telugu hits.",
        "is_featured": True,
        "is_active": True
    },
    {
        "id": "eve-003",
        "title": "Tenali Cultural & Drama Mahotsav",
        "category": "Cultural Theatre",
        "city": "tenali",
        "venue": "Tenali Ramakrishna Cultural Auditorium, Tenali",
        "date": "2025-03-29",
        "time": "18:00",
        "banner_url": "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop",
        "price_starting": 299.0,
        "description": "Celebrating the rich cultural legacy of the Paris of Andhra with mythological plays, classical music, and dance.",
        "is_featured": True,
        "is_active": True
    }
]
